### ISSUE TITLE
Incompatible with webpack 2.2.0

### ISSUE THREAD

**Issue by ndelangen** [marko-js/marko-loader#2]
This loader is incompatible with webpack 2.2.0, this is the error message I got:

```
➜  markojs git:(master) ✗ npm start

> marko-webpack@1.0.0 start /Users/dev/Projects/Playground/markojs
> npm run build && node server.js


> marko-webpack@1.0.0 build /Users/dev/Projects/Playground/markojs
> webpack

/Users/dev/Projects/Playground/markojs/node_modules/webpack/lib/Chunk.js:59
		throw new Error("Chunk.entry was removed. Use hasRuntime()");
		^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.entry (/Users/dev/Projects/Playground/markojs/node_modules/webpack/lib/Chunk.js:59:9)
    at /Users/dev/Projects/Playground/markojs/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/Users/dev/Projects/Playground/markojs/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins0 (/Users/dev/Projects/Playground/markojs/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/Users/dev/Projects/Playground/markojs/node_modules/webpack/lib/Compilation.js:533:8)
    at /Users/dev/Projects/Playground/markojs/node_modules/webpack/lib/Compiler.js:474:16
    at /Users/dev/Projects/Playground/markojs/node_modules/tapable/lib/Tapable.js:225:11
    at /Users/dev/Projects/Playground/markojs/node_modules/webpack/lib/Compilation.js:452:11
    at /Users/dev/Projects/Playground/markojs/node_modules/webpack/lib/Compilation.js:423:13
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
```

**Comment by ndelangen** [comment]
Sorry, it's not the marko-loader, it's another issue.
